server:
  port: 8000
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.0.60.60:9000/realms/techgarden
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health, info